# Generated by Django 5.0 on 2024-01-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('preco_venda', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('descricao_curta', models.TextField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagens/%Y/%m/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco_custo', models.FloatField(verbose_name='Preço')),
            ],
        ),
    ]
