# Generated by Django 5.0 on 2023-12-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0002_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
