# Generated by Django 5.0 on 2024-01-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_venda_promocional',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço promocional'),
        ),
    ]
