# Generated by Django 5.0 on 2024-01-03 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0003_produto_preco_venda_promocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lojapp.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.FloatField(verbose_name='Preço de custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço'),
        ),
    ]
