# Generated by Django 4.2.8 on 2023-12-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0003_alter_produto_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
    ]
