# Generated by Django 4.2.8 on 2023-12-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0004_rename_nome_produto_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
