# Generated by Django 4.2.8 on 2023-12-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0005_remove_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
