# Generated by Django 4.2.8 on 2023-12-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0006_alter_produto_descricao_curta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
