# Generated by Django 5.0 on 2024-01-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0006_marca_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tem_variacao',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='lojapp.produto')),
            ],
            options={
                'unique_together': {('produto', 'nome', 'valor')},
            },
        ),
    ]
