# Generated by Django 5.0 on 2024-01-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0007_alter_produto_descricao_curta'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço'),
        ),
    ]
