# Generated by Django 5.0 on 2024-01-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0007_produto_tem_variacao_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
        migrations.AddField(
            model_name='variacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
