# Generated by Django 5.0 on 2024-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0008_produto_preco_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
