# Generated by Django 5.0 on 2024-01-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0008_alter_variacao_options_variacao_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='variacao',
            unique_together={('produto', 'name', 'valor')},
        ),
    ]
