# Generated by Django 5.0 on 2024-01-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0011_valorvariacao_alter_variacao_valor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variacao',
            unique_together={('produto', 'valor')},
        ),
        migrations.AddField(
            model_name='valorvariacao',
            name='nome_variacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='lojapp.nomevariacao'),
        ),
        migrations.RemoveField(
            model_name='variacao',
            name='nome_variacao',
        ),
    ]
