# Generated by Django 5.0 on 2024-01-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0013_produto_preco_custo_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('name',), 'verbose_name': 'categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ('name',), 'verbose_name': 'marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
