# Generated by Django 5.0 on 2024-01-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0014_alter_categoria_options_alter_marca_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('name',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ('name',), 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
