# Generated by Django 5.0 on 2024-01-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0015_alter_categoria_options_alter_marca_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valorvariacao',
            unique_together={('nome_variacao', 'valor')},
        ),
    ]
