# Generated by Django 5.0 on 2024-01-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0016_alter_valorvariacao_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomevariacao',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
