# Generated by Django 5.0 on 2024-01-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0017_alter_nomevariacao_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tem_variacao',
        ),
    ]
