# Generated by Django 5.0 on 2024-01-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0018_remove_produto_tem_variacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='quantidade',
        ),
    ]
