# Generated by Django 5.0 on 2024-01-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0019_remove_variacao_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
