# Generated by Django 5.0 on 2024-01-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0020_variacao_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='quantidade',
        ),
    ]
