# Generated by Django 4.2.20 on 2025-05-11 05:26

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lojapp', '0022_alter_produto_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço de venda'),
        ),
    ]
