# Generated by Django 5.0 on 2024-01-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_venda_itemvenda_delete_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
