# Generated by Django 5.0 on 2024-01-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_alter_venda_lucro'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
