# Generated by Django 5.0 on 2024-01-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0004_itemvenda_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
