# Generated by Django 5.0 on 2024-01-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_alter_venda_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
