# Generated by Django 5.0 on 2024-01-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_alter_venda_lucro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
