# Generated by Django 5.0 on 2024-01-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0008_alter_venda_lucro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='lucro',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor_venda',
        ),
    ]
